//! Latency baseline harness (US-002, EP-001).
//!
//! Records P50 and P95 for the four operations the PRD names as the regression
//! guard for the open-core cutover (US-019 allows at most a 10% P95 regression
//! against these numbers).
//!
//! Two of the four run offline and are part of the default suite. The two that
//! touch PostgreSQL are `#[ignore]`, following the repository rule that the
//! default `cargo test` stays under two seconds with no external service.
//!
//! ```bash
//! # offline measurements
//! cargo test --test latency_baseline -- --nocapture
//!
//! # database-backed measurements
//! TEST_DATABASE_URL=postgres://... cargo test --test latency_baseline -- --ignored --nocapture
//!
//! # persist a machine-readable report
//! UPDATE_BASELINE=1 cargo test --test latency_baseline -- --nocapture
//! ```
//!
//! **Nothing here asserts a wall-clock threshold.** Absolute timings are
//! machine-dependent; a test that fails on a slow CI runner teaches people to
//! ignore it. The harness produces measurements, and
//! `docs/contracts/latency-baseline.md` records the numbers taken on the
//! reference environment. Comparison against those numbers is a deployment gate
//! (US-019), not a unit test.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};

use serde_json::json;

/// Warm-up iterations discarded before measuring.
const WARMUP: usize = 20;
/// Measured iterations per operation.
const SAMPLES: usize = 200;

// ============================================================================
// Measurement
// ============================================================================

#[derive(Debug)]
struct Measurement {
    operation: &'static str,
    samples: Vec<Duration>,
}

impl Measurement {
    fn percentile(&self, p: f64) -> Duration {
        let mut sorted = self.samples.clone();
        sorted.sort_unstable();
        // Nearest-rank: the smallest value at or above the p-th percentile.
        let rank = ((p / 100.0) * sorted.len() as f64).ceil().max(1.0) as usize;
        sorted[rank.min(sorted.len()) - 1]
    }

    fn report(&self) -> serde_json::Value {
        // Nanoseconds, not microseconds: the offline operations run in well under
        // 1 µs in release, and a microsecond field records them as 0.
        json!({
            "operation": self.operation,
            "samples": self.samples.len(),
            "p50_ns": u64::try_from(self.percentile(50.0).as_nanos()).unwrap_or(u64::MAX),
            "p95_ns": u64::try_from(self.percentile(95.0).as_nanos()).unwrap_or(u64::MAX),
        })
    }

    fn print(&self) {
        println!(
            "{:<34} n={:<4} p50={:>12.3} µs  p95={:>12.3} µs",
            self.operation,
            self.samples.len(),
            self.percentile(50.0).as_secs_f64() * 1_000_000.0,
            self.percentile(95.0).as_secs_f64() * 1_000_000.0,
        );
    }
}

fn measure<F: FnMut()>(operation: &'static str, mut op: F) -> Measurement {
    for _ in 0..WARMUP {
        op();
    }
    let mut samples = Vec::with_capacity(SAMPLES);
    for _ in 0..SAMPLES {
        let start = Instant::now();
        op();
        samples.push(start.elapsed());
    }
    Measurement { operation, samples }
}

async fn measure_async<F, Fut>(operation: &'static str, mut op: F) -> Measurement
where
    F: FnMut() -> Fut,
    Fut: std::future::Future<Output = ()>,
{
    for _ in 0..WARMUP {
        op().await;
    }
    let mut samples = Vec::with_capacity(SAMPLES);
    for _ in 0..SAMPLES {
        let start = Instant::now();
        op().await;
        samples.push(start.elapsed());
    }
    Measurement { operation, samples }
}

fn report_path(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("contracts/baseline/latency")
        .join(name)
}

fn persist(name: &str, measurements: &[Measurement]) {
    for m in measurements {
        m.print();
    }
    if std::env::var("UPDATE_BASELINE").is_ok_and(|v| v != "0" && !v.is_empty()) {
        let path = report_path(name);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let body = json!({
            "note": "Machine-dependent. Regenerated by cargo test --test latency_baseline.",
            "measurements": measurements.iter().map(Measurement::report).collect::<Vec<_>>(),
        });
        let mut rendered = serde_json::to_string_pretty(&body).unwrap();
        rendered.push('\n');
        std::fs::write(&path, rendered).unwrap();
        println!("wrote {}", path.display());
    }
}

// ============================================================================
// Offline operations
// ============================================================================

/// Source creation validation and time to first chat token.
///
/// Time to first token is measured against `FakeLlmProvider`-equivalent frames,
/// so it captures the pipeline's own overhead — stream construction, SSE
/// framing, parse — with the provider's network latency removed. That is the
/// part the open-core split can regress.
#[tokio::test]
async fn offline_latency_baseline() {
    use futures::StreamExt;
    use openbooklm::llm::{LlmStreamEvent, parse_openai_sse_data};
    use openbooklm::validation::{validate_content, validate_title, validate_url_for_ssrf};

    let title = "A representative source title";
    let content = "Synthetic source body. ".repeat(200);

    let validation = measure("source_creation_validation", || {
        validate_title(title).unwrap();
        validate_content(&content).unwrap();
        validate_url_for_ssrf("https://example.com/article").unwrap();
    });

    let first_token = measure_async("chat_time_to_first_token", || async {
        let frames: Vec<&'static str> = vec![
            "data: {\"choices\":[{\"delta\":{\"content\":\"It \"},\"index\":0}]}\n\n",
            "data: {\"choices\":[{\"delta\":{\"content\":\"says\"},\"index\":0}]}\n\n",
            "data: [DONE]\n\n",
        ];
        let mut stream = futures::stream::iter(frames);
        while let Some(frame) = stream.next().await {
            for line in frame.lines() {
                if let Some(data) = line.strip_prefix("data: ")
                    && let Some(LlmStreamEvent::TextDelta { .. }) = parse_openai_sse_data(data)
                {
                    return; // stop at the first token, which is what we measure
                }
            }
        }
        unreachable!("the synthetic stream always yields a text delta");
    })
    .await;

    assert_eq!(validation.samples.len(), SAMPLES);
    assert_eq!(first_token.samples.len(), SAMPLES);

    println!("\n-- offline latency baseline --");
    persist("offline.json", &[validation, first_token]);
}

// ============================================================================
// Database-backed operations
// ============================================================================

/// Notebooks seeded per user, and sources and chunks seeded per notebook.
///
/// The lexical measurement is only meaningful if the query matches rows. A
/// search over an empty notebook times query planning against zero tuples, not
/// retrieval, and would make the US-019 regression gate compare noise.
const SEED_NOTEBOOKS: usize = 5;
const SEED_SOURCES: usize = 4;
const SEED_CHUNKS_PER_SOURCE: usize = 40;

/// Vocabulary the seeded chunks are built from. `retrieval` appears in every
/// chunk so the measured query returns a full page of `LIMIT 15` results.
const SEED_SENTENCES: &[&str] = &[
    "Hybrid retrieval fuses dense vector search with lexical ranking.",
    "Reciprocal rank fusion combines retrieval result sets without tuning weights.",
    "The retrieval pipeline reranks candidates before assembling chat context.",
    "Parent chunks preserve retrieval context that child chunks would otherwise lose.",
];

/// Notebook listing and lexical search against a real PostgreSQL instance.
///
/// Ignored by default: the offline suite must stay under two seconds.
#[tokio::test]
#[ignore = "Requires real PostgreSQL database (TEST_DATABASE_URL env var)"]
async fn database_latency_baseline() {
    use openbooklm::core::config::DatabasePoolConfig;
    use openbooklm::repositories::{
        ChunkRepository, GenerationRepository, NotebookRepository, NotebookScope,
        SeaOrmChunkRepository, SeaOrmGenerationRepository, SeaOrmNotebookRepository,
        SeaOrmSearchRepository, SeaOrmSourceRepository, SearchRepository, SourceRepository,
    };
    use openbooklm::services::rag::provenance::{
        ChunkingProvenance, EmbeddingProvenance, GenerationProvenance, Normalization,
    };
    use openbooklm::types::{ChunkMetadata, ChunkWithContext, SourceType};

    let db_url =
        std::env::var("TEST_DATABASE_URL").expect("TEST_DATABASE_URL must be set for this test");
    let db = openbooklm::db::connect(&db_url, &DatabasePoolConfig::default())
        .await
        .expect("Failed to connect to test database");

    let notebooks = SeaOrmNotebookRepository::new(&db);
    let sources = SeaOrmSourceRepository::new(&db);
    let chunks_repo = SeaOrmChunkRepository::new(&db);
    let generations = SeaOrmGenerationRepository::new(&db);
    let search = SeaOrmSearchRepository::new(&db);

    // Seeded chunks reach search only through a published generation (EP-002).
    // The seed therefore goes through the real lifecycle rather than writing
    // rows the active pointer would never reach.
    let seed_provenance = GenerationProvenance {
        embedding: EmbeddingProvenance {
            provider: "latency-baseline".into(),
            model: "zero-vector".into(),
            dimension: openbooklm::core::providers::EMBEDDING_DIM,
            normalization: Normalization::Unknown,
        },
        chunking: ChunkingProvenance::current(1024),
    };

    // Synthetic fixture: one user, a small notebook set, and one notebook
    // populated with indexed content. This is the shape a self-hosted install
    // reaches after ingesting a handful of documents.
    //
    // The account row is required because `notebooks.user_id` references
    // `accounts(id)`. It carries an identifier and two timestamps: no email, no
    // identity subject, nothing a public fixture would have to invent (US-011).
    let user_id = uuid::Uuid::new_v4();
    {
        use openbooklm::entities::account;
        use sea_orm::{ActiveValue::Set, EntityTrait};

        let now = chrono::Utc::now().into();
        account::Entity::insert(account::ActiveModel {
            id: Set(user_id),
            created_at: Set(now),
            updated_at: Set(now),
        })
        .exec(&db)
        .await
        .expect("create synthetic account");
    }

    let mut created = Vec::new();
    for i in 0..SEED_NOTEBOOKS {
        created.push(
            notebooks
                .create(user_id, format!("Baseline notebook {i}"), None)
                .await
                .expect("create notebook"),
        );
    }
    let notebook_id = created[0].id;

    let mut seeded_chunks = 0usize;
    for s in 0..SEED_SOURCES {
        let source = sources
            .create(
                notebook_id,
                format!("Baseline source {s}"),
                SourceType::Text,
                SEED_SENTENCES.join(" "),
                None,
            )
            .await
            .expect("create source");

        let chunks: Vec<ChunkWithContext> = (0..SEED_CHUNKS_PER_SOURCE)
            .map(|c| {
                let sentence = SEED_SENTENCES[c % SEED_SENTENCES.len()];
                ChunkWithContext {
                    content: format!("{sentence} Passage {c} of baseline source {s}."),
                    context_prefix: None,
                    parent_content: None,
                    metadata: ChunkMetadata {
                        position: u32::try_from(c).unwrap_or(0),
                        ..Default::default()
                    },
                    content_hash: String::new(),
                }
            })
            .collect();
        // Zero vectors: this measurement is lexical, and the embedding values do
        // not affect the tsvector path. Dimension must still match the schema.
        let embeddings: Vec<Vec<f32>> = vec![vec![0.0; 1024]; chunks.len()];

        let generation_id = generations
            .claim(source.id, &seed_provenance)
            .await
            .expect("claim generation")
            .expect("a fresh source has no competing build");
        chunks_repo
            .store_chunks(generation_id, source.id, &chunks, &embeddings)
            .await
            .expect("store chunks");
        generations
            .record_build_plan(
                generation_id,
                i32::try_from(chunks.len()).expect("seed size fits in i32"),
                &seed_provenance.chunking,
            )
            .await
            .expect("record build plan");
        let _published = generations
            .publish(
                generation_id,
                source.id,
                openbooklm::core::providers::EMBEDDING_DIM,
            )
            .await
            .expect("publish generation");
        seeded_chunks += chunks.len();
    }

    // Fail loudly rather than record a meaningless number: a lexical baseline
    // over an empty result set is not a baseline.
    let hits = search
        .search_lexical_chunks(NotebookScope::new(user_id, notebook_id), "retrieval", 15)
        .await
        .expect("lexical search");
    assert!(
        !hits.is_empty(),
        "seeded {seeded_chunks} chunks but lexical search returned none; \
         the tsvector index or the seed vocabulary is wrong, and the measurement \
         below would be meaningless"
    );
    println!(
        "seeded {seeded_chunks} chunks across {SEED_SOURCES} sources; \
         lexical query returns {} rows",
        hits.len()
    );

    let listing = measure_async("notebook_listing", || async {
        notebooks
            .list_with_source_counts(user_id)
            .await
            .expect("list notebooks");
    })
    .await;

    let lexical = measure_async("lexical_search", || async {
        search
            .search_lexical_chunks(NotebookScope::new(user_id, notebook_id), "retrieval", 15)
            .await
            .expect("lexical search");
    })
    .await;

    // Deleting the account cascades to notebooks, sources and chunks, so the
    // measurement leaves no rows behind.
    {
        use openbooklm::entities::account;
        use sea_orm::EntityTrait;

        account::Entity::delete_by_id(user_id)
            .exec(&db)
            .await
            .expect("cleanup synthetic account");
    }

    println!("\n-- database latency baseline --");
    persist("database.json", &[listing, lexical]);
}
